### ISSUE TITLE
Output files (html, pdf, & epub) do not include embedded images

### ISSUE THREAD

**Issue by diedrichg** [razziel89/mealie-addons#6]
Output files for html, pdf, and epub do not include the embedded images that are added to individual instruction steps.

I have a few recipes that contain images in the instructions - those images are not being included. (This is the html output)

![Image](https://github.com/user-attachments/assets/5546a7e2-aef6-4b76-b968-786a32385293)

**Comment by razziel89** [comment]
Interesting! I didn't know you could add images to individual steps. I'd have to look at the raw JSON of a recipe with such a step to be able to debug this. Basically, I'm wondering how mealie encodes the fact that there are images attached to a step in the JOSN encoding. So far, I believed that all it would allow was markdown formatting. 

Only on mobile again so I cannot try it out myself. It seems you cannot add images to steps on mobile since you'd have to drag and drop them in.

If you could provide the exported markdown version for that exact same recipe, that would also already help.

**Comment by diedrichg** [comment]
Yep, it's pretty cool

![Image](https://github.com/user-attachments/assets/da5c71b3-9464-4648-b7d7-481bdfee7eb5)

Does this help?
```html
<!DOCTYPE html>
<html data-n-head="%7B%22lang%22:%7B%221%22:%22en%22%7D%7D" lang="en">
<head>
<meta content="website" data-hid="og:type" data-n-head="1" property="og:type"/><meta content="Salmon Wellington" data-hid="og:title" data-n-head="1" property="og:title"/><meta content="Mealie" data-hid="og:site_name" data-n-head="1" property="og:site_name"/><meta content="" data-hid="og:description" data-n-head="1" property="og:description"/><meta content="https://domain/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/images/original.webp?version=192" data-hid="og:image" data-n-head="1" property="og:image"/><meta charset="utf-8" data-n-head="1"/><meta content="width=device-width,initial-scale=1" data-n-head="1" name="viewport"/><meta content="Mealie is a recipe management app for your kitchen." data-hid="description" data-n-head="1" name="description"/><meta charset="utf-8" data-hid="charset" data-n-head="1"/><meta content="yes" data-hid="mobile-web-app-capable" data-n-head="1" name="mobile-web-app-capable"/><meta content="Mealie" data-hid="apple-mobile-web-app-title" data-n-head="1" name="apple-mobile-web-app-title"/><meta content="#E58325" data-hid="theme-color" data-n-head="1" name="theme-color"/><title>Mealie</title><link data-hid="favicon" data-n-head="1" href="[/favicon.ico](view-source:https://domain/favicon.ico)" rel="icon" type="image/x-icon"/><link data-hid="shortcut icon" data-n-head="1" href="[/icons/icon-x64.png](view-source:https://domain/icons/icon-x64.png)" rel="shortcut icon" type="image/png"/><link data-hid="apple-touch-icon" data-n-head="1" href="[/icons/apple-touch-icon.png](view-source:https://domain/icons/apple-touch-icon.png)" rel="apple-touch-icon" type="image/png"/><link data-hid="mask-icon" data-n-head="1" href="[/icons/safari-pinned-tab.svg](view-source:https://domain/icons/safari-pinned-tab.svg)" rel="mask-icon"/><link data-n-head="1" href="[/icons/android-chrome-192x192.png](view-source:https://domain/icons/android-chrome-192x192.png)" rel="shortcut icon"/><link data-n-head="1" href="[/icons/android-chrome-maskable-512x512.png](view-source:https://domain/icons/android-chrome-maskable-512x512.png)" rel="apple-touch-icon" sizes="512x512"/><link crossorigin="use-credentials" data-hid="manifest" data-n-head="1" href="[/_nuxt/manifest.a4e417a0.json](view-source:https://domain/_nuxt/manifest.a4e417a0.json)" rel="manifest"/><base href="[/](view-source:https://domain/)"/><link as="script" href="[/_nuxt/3fe2beb.js](view-source:https://domain/_nuxt/3fe2beb.js)" rel="preload"/><link as="script" href="[/_nuxt/9fa1655.js](view-source:https://domain/_nuxt/9fa1655.js)" rel="preload"/><link as="script" href="[/_nuxt/4d62cd7.js](view-source:https://domain/_nuxt/4d62cd7.js)" rel="preload"/><link as="script" href="[/_nuxt/57197a2.js](view-source:https://domain/_nuxt/57197a2.js)" rel="preload"/>
<script type="application/ld+json">{"@context": "https://schema.org", "@type": "Recipe", "name": "Salmon Wellington", "description": "", "image": ["https://domain/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/images/original.webp?version=192"], "datePublished": "2024-04-17T20:06:49.277247+00:00", "prepTime": null, "cookTime": null, "totalTime": null, "recipeYield": "0.0", "recipeIngredient": ["4 (7 oz) salmon fillets", "salt and pepper to taste", "2 tbsp butter", "2 garlic cloves, minced", "1 shallot, chopped", "1/4 cup white wine", "3 oz cream cheese", "5 oz fresh baby spinach", "2 tbsp plain bread crumbs", "1/4 cup shredded parmesan cheese", "1 (1 lb.) package puff pastry", "1 egg (for egg wash)"], "recipeInstructions": ["Season the salmon with salt and pepper to taste.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-2-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "In a pan, heat butter, chopped shallots, and garlic over medium heat. Saut\u00e9 until the shallots become translucent.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-3-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "Bring the heat to high and add the white wine. Let the liquid cook out for about 5 minute, then add the cream cheese and saut\u00e9 for 1 minute.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-5-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "Lastly, add the spinach, bread crumbs, and Parmesan cheese.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-7-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "Unfold the puff pastry onto a light floured surface and roll out the 2 sheets, then cut them in half. So you end up with 4 pieces. I made each piece about 10X 14 inches.aut\u00e9 just until the the spinach softens.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-12-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "Place each seasoned salmon fillet in the middle of each puff pastry sheet. Depending on the size of the fillet, you may need to roll out the puff pastry a little more or less. Leave about 2 inches around the edges.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-13-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "Divide the spinach mixture into 4 equal parts and evenly spread it on top of the 4 fillets. Then brush the edges of the puff pastry with egg wash (1 egg + 1 tsp water).<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-15-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "Begin folding the the puff pastry over starting with the longer side. When folding over the short edges, brush more of the egg wash before folding.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-18-jpg.jpg\" height=\"100%\" width=\"100%\"/><img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-20-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "Line a baking sheet with parchment paper and place the salmon wellington seam side down.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-21-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "Make crosshatch slits on top of the Wellington with a knife. Then brush with more egg wash.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-22-jpg.jpg\" height=\"100%\" width=\"100%\"/><img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-23-jpg.jpg\" height=\"100%\" width=\"100%\"/>", "Bake at 390 degrees Fahrenheit for 25-30 minutes or until the pastry is golden brown.<img src=\"/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/assets/salmon-wellington-24-jpg.jpg\" height=\"100%\" width=\"100%\"/>"], "recipeCategory": ["Main Dishes"], "keywords": ["DVGMAR", "Seafood", "Vegetarian", "Internet"], "nutrition": {"calories": null, "carbohydrateContent": null, "cholesterolContent": null, "fatContent": null, "fiberContent": null, "proteinContent": null, "saturatedFatContent": null, "sodiumContent": null, "sugarContent": null, "transFatContent": null, "unsaturatedFatContent": null}}</script>
<meta content="https://domain/g/home/r/salmon-wellington" data-hid="og:url" data-n-head="1" property="og:url"/><meta content="summary_large_image" data-hid="twitter:card" data-n-head="1" property="twitter:card"/><meta content="Salmon Wellington" data-hid="twitter:title" data-n-head="1" property="twitter:title"/><meta content="" data-hid="twitter:description" data-n-head="1" property="twitter:description"/><meta content="https://domain/api/media/recipes/da2bf797-1bdd-4206-92cd-7c194b491135/images/original.webp?version=192" data-hid="twitter:image" data-n-head="1" property="twitter:image"/><meta content="https://domain/g/home/r/salmon-wellington" data-hid="twitter:url" data-n-head="1" property="twitter:url"/></head>
<body>
<div id="__nuxt"><style>#nuxt-loading{background:#fff;visibility:hidden;opacity:0;position:absolute;left:0;right:0;top:0;bottom:0;display:flex;justify-content:center;align-items:center;flex-direction:column;animation:nuxtLoadingIn 10s ease;-webkit-animation:nuxtLoadingIn 10s ease;animation-fill-mode:forwards;overflow:hidden}@keyframes nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}@-webkit-keyframes nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}#nuxt-loading>div,#nuxt-loading>div:after{border-radius:50%;width:5rem;height:5rem}#nuxt-loading>div{font-size:10px;position:relative;text-indent:-9999em;border:.5rem solid #f5f5f5;border-left:.5rem solid #000;-webkit-transform:translateZ(0);-ms-transform:translateZ(0);transform:translateZ(0);-webkit-animation:nuxtLoading 1.1s infinite linear;animation:nuxtLoading 1.1s infinite linear}#nuxt-loading.error>div{border-left:.5rem solid #ff4500;animation-duration:5s}@-webkit-keyframes nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}@keyframes nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}</style> <script>window.addEventListener("error",function(){var e=document.getElementById("nuxt-loading");e&&(e.className+=" error")})</script> <div aria-live="polite" id="nuxt-loading" role="status"><div>Loading...</div></div> </div><script>window.__NUXT__=function(r,n,a,s,e,c,o){return{config:{GLOBAL_MIDDLEWARE:null,SUB_PATH:"",axios:{browserBaseURL:""},useDark:!1,themes:{dark:{primary:r,accent:n,secondary:a,success:s,info:e,warning:c,error:o,background:"#1E1E1E"},light:{primary:r,accent:n,secondary:a,success:s,info:e,warning:c,error:o}},_app:{basePath:"/",assetsPath:"/_nuxt/",cdnURL:null}}}}("#E58325","#007A99","#973542","#43A047","#1976d2","#FF6D00","#EF5350")</script>
<script src="[/_nuxt/3fe2beb.js](view-source:https://domain/_nuxt/3fe2beb.js)"></script><script src="[/_nuxt/9fa1655.js](view-source:https://domain/_nuxt/9fa1655.js)"></script><script src="[/_nuxt/4d62cd7.js](view-source:https://domain/_nuxt/4d62cd7.js)"></script><script src="[/_nuxt/57197a2.js](view-source:https://domain/_nuxt/57197a2.js)"></script></body>
</html>
```

**Comment by diedrichg** [comment]
Until a fix is made for embedded images, would there be a way to disregard images so that users can publish a PDF?

**Comment by razziel89** [comment]
Yes, that's the workaround I wanted to implement first. I've found the time to make a new release that is supposed to remove embedded images from instructions. It's not perfect but it's the best I could do in the shortness of time. Could you please try it out if time permits?

Some cases where this quick fix will break:

- If the file name contains a double quote character `"`.
- If the HTML that mealie dumps into the instruction step contains a slash other than the one at the end, closing the `img` HTML element. Mealie does not add something like that based on my quick tests. The slashes in the file name are fine.
- If the HTML is modified in a such a way that a slash is added.
- If the `src` attribute does not follow the start of the `img` element directly. Based on my tests, it always does when dragging and dropping an image into an instruction step. 

I know how to fix this properly, but that would have taken more time than available.

Does the new release work for you?

**Comment by diedrichg** [comment]
> Does the new release work for you?

Works well, the PDF was created! There are a few character errors that weren't an issue previously when creating an HTML file.

![Image](https://github.com/user-attachments/assets/29e647c9-9a28-41f9-8550-9b9f4e514660)

Here is the pdf output, the Salmon Wellington was one of the recipes with images. 

![Image](https://github.com/user-attachments/assets/fd791f56-df61-4be7-92c1-3e984ebce4ea)

**Comment by razziel89** [comment]
Great to hear that it worked! I also got those character errors in a few recipes. Unfortunately, I haven't yet found a way to resolve them. Basically the problem is that the font pandoc uses by default in pdfs doesn't provide all the characters known to Unicode. The font will have to be replaced or a fallback font has to be set up, if pandoc even supports that. The reason it works in the html is that browsers fall back to other fonts automatically. As long as there is one font installed that contains a glyph, it will be rendered. LaTeX, which pandoc uses to create pdfs, does not support that out of the box, as far as I know.

**Comment by razziel89** [comment]
One quick fix you could try is using the following pandoc flags:

```
PNDOC_FLAGS: |-
  --variable=header-includes:\usepackage[utf8x]{inputenc}
```

It will lause LaTeX to try and replace Unicode characters by their equivalent LaTeX code. It might work. I cannot try anything during the next days, but this possible workaround just came to mind.

If that doesn't work, you could try replacing `utf8x` by just `utf8`.

**Comment by diedrichg** [comment]
how do I string together multiple flags as a single line? e.g.
```
--epub-title-page=false --variable=header-includes:\usepackage[utf8x]{inputenc}
``` 
???

**Comment by razziel89** [comment]
That is not currently possible. Multiple flags have to be separated by line breaks in the current version, as stated in the documentation for the PANDOC_FLAGS environment variable. For testing, if your system doesn't allow specifying a multi-line string, you could remove the flag regarding the EPUB title page.

It would be relatively easy to support arbitrary user-defined separators, but I'd have to be at a computer to add that feature.

**Comment by diedrichg** [comment]
EDIT: I know you are busy. No need to reply to this or try to fix it. You'll get to it when you have time.

Using just the --variable=header-includes:\usepackage[utf8x]{inputenc}    flag I still got the same character errors

```
2025/02/16 11:03:26 removed embedded image from text: Reduce oven temperature to 325 degrees on convection roast setting. Melt remaining 1 tablespoon butter and brush evenly over turkey. Return turkey to oven and continue to roast until skin is deep golden brown and breast registers 155 degrees and thighs register 175 degrees, 2 to 2½ hours longer. Total cooking time, uncovered, at 325° on convection roast setting is about 13 minutes per pound.<img src="/api/media/recipes/7dcbdf51-d47e-4f0f-8088-c630db2dabba/assets/1000007777-jpg.jpg" height="100%" width="100%"/>
2025/02/16 11:03:26 running pandoc with args: --standalone --pdf-engine=xelatex --variable=geometry:margin=2cm --variable=header-includes:\usepackage[utf8x]{inputenc} --from=markdown --to=html --output=-
2025/02/16 11:03:30 running pandoc with args: --standalone --pdf-engine=xelatex --variable=geometry:margin=2cm --variable=header-includes:\usepackage[utf8x]{inputenc} --from=markdown --to=html --output=- --from=html --to pdf
2025/02/16 11:03:41 stderr when running pandoc: [WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅔ (U+2154) (U+2154) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅔ (U+2154) (U+2154) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅔ (U+2154) (U+2154) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no   (U+2003) (U+2003) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅔ (U+2154) (U+2154) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅔ (U+2154) (U+2154) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ℉ (U+2109) (U+2109) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅓ (U+2153) (U+2153) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅔ (U+2154) (U+2154) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅔ (U+2154) (U+2154) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no ⅛ (U+215B) (U+215B) in font [lmroman10-regular]:mapping=t

2025/02/16 11:03:41 written 709559 bytes, expected 709559 bytes
2025/02/16 11:03:41 application/pdf endpoint accessed successfully
[GIN] 2025/02/16 - 11:03:41 | 200 |  24.08338095s |    10.83.20.254 | GET      "/book/pdf"
``` 

I did notice, however that the \ in the variable may be escaping the flag functions because it's showing up at the top of the html file.

![Image](https://github.com/user-attachments/assets/3b00a27d-51a2-4a5e-89be-43ec3f8c1862)

**Comment by razziel89** [comment]
I've released version 0.2.3 that adds the package differently. In my tests, I've found that many unicode characters are now correctly displayed, even if the font used by default doesn't contain them, because they are replaced by appropriate LaTeX macros. Can you please give it another try?

**Comment by diedrichg** [comment]
Still a few that are falling through the cracks
EDIT:  I ran the html and I'm still seeing the `\usepackage[utf8x]{inputenc}` printed at the top of the page.  I don't think this variable is being used and the \ is escaping the remainder of the variable.

![Image](https://github.com/user-attachments/assets/cdcbbd76-e545-4bfe-96b7-5d7979619bf9)

Here is the PDF, note the chopped parsley 

![Image](https://github.com/user-attachments/assets/00724b28-471e-46ae-9a49-74aafe5a9684)

Here is the Mealie recipe

![Image](https://github.com/user-attachments/assets/bb231eab-8880-4bb3-b4bc-04e7440f8b44)

Here is the character
⅓

**Comment by razziel89** [comment]
> I ran the html and I'm still seeing the \usepackage[utf8x]{inputenc} printed at the top of the page.

Have you removed the specification from your `PANDOC_FLAGS`? You no longer have to add the usepackage instruction to the `PANDOC_FLAGS`, the instruction is automatically included in the most recent release.

Are you sure you are using the most recent docker image?  What is the hash of the image you are using? The hash of the most recent image is always shown at the top of [this page](https://github.com/razziel89/mealie-addons/pkgs/container/mealie-addons) (hoping you can access that page). At the moment, it is `sha256-1f62e70f4b7e632c3d9d4a464f41bf450a392032b0e49a4f9a8b2f043c072ec9`.

> Here is the character
> ⅓

Every solution to this problem that I could come up with hinges on switching to `lualatex` as PDF engine instead of `xelatex`. However, until now, I haven't managed to create a single PDF with the `lualatex` engine. Until the switch has been made, the only possible workaround that I can see is to manually replace characters such as `⅓` by a close ASCII equivalent such as `1/3` or maybe `0.33` in every affected recipe.

We might want to continue discussing the font topic in a separate issue and reserve this issue for the topic of embedded images.

**Comment by razziel89** [comment]
One of my tests today was successful. I had a pdf built with lualatex and it used multiple fallback fonts. I'll follow up on those results sometime soon.

**Comment by razziel89** [comment]
I've released a new version of the docker image that contains fonts that cover a large number of the glyphs specified by unicode. It fixed all the problems with missing characters for me. The downside is that PDF generation takes longer, but that probably cannot be helped. It is also possible to bring one's own fonts and have them loaded then starting `mealie-addons`, but that feature is not yet documented. Basically, the variable `PANDOC_FONTS_DIR` has to point to a directory. All `*.ttf` files in tha directory will be loaded as fonts. A file named `main.ttf` will be used as main font and all others as fallback. The list of fallback fonts is sorted alphabetically.

**Comment by razziel89** [comment]
I've released version 0.4.0 that supports the as-yet undocumented environment variable `MA_IMAGE_ACTION`. The default value is `remove`. When set to `embed`, images will be embedded in the documents, apart from markdown, which does not really support embedding images. The output files will contain both the title images of each recipe that has one ad well as images embedded in each instruction.

Could you please try it out, if time permits, @diedrichg? With the most recent release, I would consider this issue closed. There still isn't a good and simple way to adjust the formatting of the output document, but one step at a time. Formatting should not be part of this issue.

What do you think?

**Comment by razziel89** [comment]
I've released 0.5.0, which also contains the documentation for this feature. There are now also `MA_HTML_ATTRS_MOD` and `MA_HTML_ATTRS_RM` that make it easy to modify the document to some extent.

With that release, I'll close this issue.
